server:
  port: 8080
custom:
    welcomeMsg: Hello from Test
---
spring:
  config:
    activate:
      on-profile: prod
server:
  port: 5000
custom:
  welcomeMsg: Hello from Prod
---
spring:
  config:
    activate:
      on-profile: test
server:
  port: 4000
custom:
  welcomeMsg: Hello from Test
